# Generated by Django 5.1.4 on 2024-12-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
