# Generated by Django 5.1.4 on 2024-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0005_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[('Easy', 0), ('Normal', 1), ('Hard', 2)]),
        ),
    ]
