# Generated by Django 5.1.4 on 2024-12-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0006_alter_game_level_of_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Normal'), (2, 'Hard')]),
        ),
    ]
